### ISSUE TITLE
Add support for Ubuntu 16.04 (and 18.04)

### ISSUE THREAD

**Issue by MatthewJohn** [ITDevLtd/MCVirt#299]
TODO:
* Ubuntu 16.04:
  - [x] Test build and installation
  - [x] Successful unit tests single instance (https://github.com/ITDevLtd/MCVirt/issues/299#issuecomment-422808993)
  - [x] Successful unit tests cluster without DRBD (https://github.com/ITDevLtd/MCVirt/issues/299#issuecomment-423815009)
  - [x] Successful unit tests on cluster with DRBD (https://github.com/ITDevLtd/MCVirt/issues/299#issuecomment-423816047)
  - [x] Fix issues with libvirt restart (see https://github.com/ITDevLtd/MCVirt/issues/299#issuecomment-423738646) (fixed in 5e698bb)
  - [x] Investigate output from Pyro (see https://github.com/ITDevLtd/MCVirt/issues/299#issuecomment-422808993)
  - [x] Logging appears to be broken (see https://github.com/ITDevLtd/MCVirt/issues/299#issuecomment-423814429)
* Ubuntu 18.04:
  - [ ] Test build and installation
  - [ ] Successful unit tests single instance
  - [ ] Successful unit tests on cluster with DRBD
  - [ ] Ensure libvirt is restarted correctly

**Comment by MatthewJohn** [comment]
First tests on 16.04, without DRBD. Installed fine, tests completed:

``
test_add_remove_user_vm_permission (mcvirt.test.auth_tests.AuthTests)
Permission permission tests using VM role ... ok
test_add_remove_user_global_permission (mcvirt.test.auth_tests.AuthTests)
Permission permission tests using global role ... ok
test_add_delete_superuser (mcvirt.test.auth_tests.AuthTests)
Add/delete a user to/from the superuser role ... ok
test_attempt_add_superuser_to_vm (mcvirt.test.auth_tests.AuthTests)
Attempts to add a user as a superuser to a VM ... ok
test_add_duplicate_superuser (mcvirt.test.auth_tests.AuthTests)
Attempts to add a superuser twice ... ok
test_delete_non_existant_superuser (mcvirt.test.auth_tests.AuthTests)
Attempts to remove a non-existent user from the superuser group ... ok
test_change_password (mcvirt.test.auth_tests.AuthTests)
Change the password of a user through the parser ... ok
test_add_new_user (mcvirt.test.auth_tests.AuthTests)
Create a new user through the parser ... ok
test_remove_user_account (mcvirt.test.auth_tests.AuthTests)
Delete a user through the parser ... ok
test_create_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_create test with Local storage ... ok
test_delete_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_delete test with Local storage ... ok
test_invalid_name (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create a virtual machine with an invalid name ... ok
test_create_duplicate (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create two VMs with the same name ... ok
test_vm_directory_already_exists (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create a VM whilst the directory for the VM already exists ... ok
test_start_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_start test with Local storage ... ok
test_start_running_vm (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to start a running VM ... ok
test_reset (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Reset a running VM ... ok
test_reset_stopped_vm (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to reset a stopped VM ... ok
test_lock (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Exercise VM locking ... ok
test_stop_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_stop test with Local storage ... ok
test_stop_stopped_vm (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to stop an already stopped VM ... ok
test_clone_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Test the VM cloning in MCVirt using the argument parser ... ok
test_duplicate_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform test_duplicate test with Local storage ... ok
test_unspecified_storage_type_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... ok
test_invalid_network_name (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create a VM using a network that does not exist ... ok
test_create_alternative_driver (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Create VMs using alternative hard drive drivers ... ok
test_live_iso_change (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Change the ISO attached to a running VM ... ok
test_create_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_delete_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_start_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_stop_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_create_drbd_not_enabled (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... ok
test_offline_migrate (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_clone_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_duplicate_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_unspecified_storage_type_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_create (mcvirt.test.node.network_tests.NetworkTests)
Test the creation of network through the argument parser ... ok
test_duplicate_name_create (mcvirt.test.node.network_tests.NetworkTests)
Test attempting to create a network with a duplicate name through the argument parser ... ok
test_delete (mcvirt.test.node.network_tests.NetworkTests)
Test deleting a network through the argument parser ... ok
test_delete_non_existent (mcvirt.test.node.network_tests.NetworkTests)
Attempt to delete a non-existent network ... ok
test_delete_utilized (mcvirt.test.node.network_tests.NetworkTests)
Attempt to remove a network that is in use by a VM ... ok
test_list (mcvirt.test.node.network_tests.NetworkTests)
Attempt to use the parser to list the networks ... ok
test_verify (mcvirt.test.virtual_machine.hard_drive.drbd_tests.DrbdTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_remove_network (mcvirt.test.update_tests.UpdateTests)
Remove a network interface from a VM, using the ... ok
test_remove_network_non_existant (mcvirt.test.update_tests.UpdateTests)
Attempt to remove a network interface from a VM ... ok
test_set_windows_flag (mcvirt.test.update_tests.UpdateTests)
Set the Windows CPU flag and check the XML is modified correctly ... ok
test_set_ip_address (mcvirt.test.node.node_tests.NodeTests)
Change the cluster IP address using the argument parser ... ok
test_set_invalid_ip_address (mcvirt.test.node.node_tests.NodeTests)
Test the validity checks for IP addresses uses ArgumentValidator ... ok
test_set_volume_group (mcvirt.test.node.node_tests.NodeTests)
Change the cluster IP address using the argument parser ... ok
test_set_invalid_volume_group (mcvirt.test.node.node_tests.NodeTests)
Test the validity checks for volume group name uses ArgumentValidator ... ok
test_migrate_locked (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_unregistered (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_inappropriate_node (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_drbd_not_connected (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_invalid_network (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_invalid_iso (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_invalid_node (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_pre_migration_libvirt_failure (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_post_migration_libvirt_failure (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_libvirt_connection_failure (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_stopped_vm (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_create_vm (mcvirt.test.validation_tests.ValidationTests)
Test an invalid VM name to check that VM creation uses ArgumentValidator ... ok
test_create_network (mcvirt.test.validation_tests.ValidationTests)
Test creating a netork with an invalid name to check that network creation uses ... ok
test_hostnames (mcvirt.test.validation_tests.ValidationTests)
Test the validation of hostnames ... ok
test_network_names (mcvirt.test.validation_tests.ValidationTests)
Test the validation of network names ... ok
test_integer (mcvirt.test.validation_tests.ValidationTests)
Test the validation of integers ... ok
test_pos_integer (mcvirt.test.validation_tests.ValidationTests)
Test the validation of positive integers ... ok
test_boolean (mcvirt.test.validation_tests.ValidationTests)
Test the validation of booleans ... ok
test_drbd_resource (mcvirt.test.validation_tests.ValidationTests)
Test the validation of DRBD resource names ... ok
test_ip_address (mcvirt.test.validation_tests.ValidationTests)
Test the validation of IP addresses ... ok
test_vg_name (mcvirt.test.validation_tests.ValidationTests) ... ok
test_method_lock_rpc (mcvirt.test.lock.lock_tests.LockTests)
Test whether locks can be cleared over the RPC ... ok
test_method_lock_escape_return (mcvirt.test.lock.lock_tests.LockTests)
Test whether locks can be cleared and clear_method_lock returns accurateley ... ok
test_valid_user (mcvirt.test.ldap_tests.LdapTests)
Test running a command with valid Ldap credentials ... ok
test_invalid_user (mcvirt.test.ldap_tests.LdapTests)
Test running a command with invalid Ldap credentials ... ok
test_parser (mcvirt.test.ldap_tests.LdapTests)
Test the Ldap options work correctly in the parser ... ok
test_user_search (mcvirt.test.ldap_tests.LdapTests)
Test that getting LDAP usernames takes the user_search attribute into account ... ok

----------------------------------------------------------------------
Ran 78 tests in 61.205s

OK (skipped=21)
``

**Comment by MatthewJohn** [comment]
Restarting libvirtd fails on Ubuntu 16.04, this causes issues when:
* Restarting machine (need to stop and kill libvirtd before starting - might be a bug with libvirtd?)
* Adding a node to a cluster (struggling to find temporary work-around)

**Comment by MatthewJohn** [comment]
Logging appears to be broken and no logs are being outputted to /var/log/mcvirt.log or syslog, apart from during shutdown

**Comment by MatthewJohn** [comment]
> Logging appears to be broken and no logs are being outputted to /var/log/mcvirt.log or syslog, apart from during shutdown

Changing the log level in the mcvirt configuration appears to make this work... so appears that the issue is that /etc/default/mcvirtd is not being used for environment variables in startup. Maybe an issue with the init script.

**Comment by MatthewJohn** [comment]
16.04 Cluster run without DRBD:
```
libvirt: Network Driver error : Network not found: no network with matching name 'default'
test_add_remove_user_vm_permission (mcvirt.test.auth_tests.AuthTests)
Permission permission tests using VM role ... ok
test_add_remove_user_global_permission (mcvirt.test.auth_tests.AuthTests)
Permission permission tests using global role ... ok
test_add_delete_superuser (mcvirt.test.auth_tests.AuthTests)
Add/delete a user to/from the superuser role ... ok
test_attempt_add_superuser_to_vm (mcvirt.test.auth_tests.AuthTests)
Attempts to add a user as a superuser to a VM ... ok
test_add_duplicate_superuser (mcvirt.test.auth_tests.AuthTests)
Attempts to add a superuser twice ... ok
test_delete_non_existant_superuser (mcvirt.test.auth_tests.AuthTests)
Attempts to remove a non-existent user from the superuser group ... ok
test_change_password (mcvirt.test.auth_tests.AuthTests)
Change the password of a user through the parser ... ok
test_add_new_user (mcvirt.test.auth_tests.AuthTests)
Create a new user through the parser ... ok
test_remove_user_account (mcvirt.test.auth_tests.AuthTests)
Delete a user through the parser ... ok
test_create_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_create test with Local storage ... ok
test_delete_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_delete test with Local storage ... ok
test_invalid_name (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create a virtual machine with an invalid name ... ok
test_create_duplicate (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create two VMs with the same name ... ok
test_vm_directory_already_exists (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create a VM whilst the directory for the VM already exists ... ok
test_start_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_start test with Local storage ... ok
test_start_running_vm (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to start a running VM ... ok
test_reset (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Reset a running VM ... ok
test_reset_stopped_vm (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to reset a stopped VM ... ok
test_lock (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Exercise VM locking ... ok
test_stop_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform the test_stop test with Local storage ... ok
test_stop_stopped_vm (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to stop an already stopped VM ... ok
test_clone_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Test the VM cloning in MCVirt using the argument parser ... ok
test_duplicate_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Perform test_duplicate test with Local storage ... ok
test_unspecified_storage_type_local (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... ok
test_invalid_network_name (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Attempt to create a VM using a network that does not exist ... ok
test_create_alternative_driver (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Create VMs using alternative hard drive drivers ... ok
test_live_iso_change (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests)
Change the ISO attached to a running VM ... ok
test_create_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_delete_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_start_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_stop_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_create_drbd_not_enabled (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... ok
test_offline_migrate (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_clone_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_duplicate_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_unspecified_storage_type_drbd (mcvirt.test.virtual_machine.virtual_machine_tests.VirtualMachineTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_create (mcvirt.test.node.network_tests.NetworkTests)
Test the creation of network through the argument parser ... ok
test_duplicate_name_create (mcvirt.test.node.network_tests.NetworkTests)
Test attempting to create a network with a duplicate name through the argument parser ... ok
test_delete (mcvirt.test.node.network_tests.NetworkTests)
Test deleting a network through the argument parser ... ok
test_delete_non_existent (mcvirt.test.node.network_tests.NetworkTests)
Attempt to delete a non-existent network ... ok
test_delete_utilized (mcvirt.test.node.network_tests.NetworkTests)
Attempt to remove a network that is in use by a VM ... ok
test_list (mcvirt.test.node.network_tests.NetworkTests)
Attempt to use the parser to list the networks ... ok
test_verify (mcvirt.test.virtual_machine.hard_drive.drbd_tests.DrbdTests) ... skipped "DRBD either required and not available or can't be present and is installed."
test_remove_network (mcvirt.test.update_tests.UpdateTests)
Remove a network interface from a VM, using the ... ok
test_remove_network_non_existant (mcvirt.test.update_tests.UpdateTests)
Attempt to remove a network interface from a VM ... ok
test_set_windows_flag (mcvirt.test.update_tests.UpdateTests)
Set the Windows CPU flag and check the XML is modified correctly ... ok
test_set_ip_address (mcvirt.test.node.node_tests.NodeTests)
Change the cluster IP address using the argument parser ... ok
test_set_invalid_ip_address (mcvirt.test.node.node_tests.NodeTests)
Test the validity checks for IP addresses uses ArgumentValidator ... ok
test_set_volume_group (mcvirt.test.node.node_tests.NodeTests)
Change the cluster IP address using the argument parser ... ok
test_set_invalid_volume_group (mcvirt.test.node.node_tests.NodeTests)
Test the validity checks for volume group name uses ArgumentValidator ... ok
test_migrate_locked (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_unregistered (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_inappropriate_node (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_drbd_not_connected (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_invalid_network (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_invalid_iso (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_invalid_node (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_pre_migration_libvirt_failure (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_post_migration_libvirt_failure (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_libvirt_connection_failure (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate_stopped_vm (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_migrate (mcvirt.test.virtual_machine.online_migrate_tests.OnlineMigrateTests) ... skipped 'DRBD is not enabled on this node'
test_create_vm (mcvirt.test.validation_tests.ValidationTests)
Test an invalid VM name to check that VM creation uses ArgumentValidator ... ok
test_create_network (mcvirt.test.validation_tests.ValidationTests)
Test creating a netork with an invalid name to check that network creation uses ... ok
test_hostnames (mcvirt.test.validation_tests.ValidationTests)
Test the validation of hostnames ... ok
test_network_names (mcvirt.test.validation_tests.ValidationTests)
Test the validation of network names ... ok
test_integer (mcvirt.test.validation_tests.ValidationTests)
Test the validation of integers ... ok
test_pos_integer (mcvirt.test.validation_tests.ValidationTests)
Test the validation of positive integers ... ok
test_boolean (mcvirt.test.validation_tests.ValidationTests)
Test the validation of booleans ... ok
test_drbd_resource (mcvirt.test.validation_tests.ValidationTests)
Test the validation of DRBD resource names ... ok
test_ip_address (mcvirt.test.validation_tests.ValidationTests)
Test the validation of IP addresses ... ok
test_vg_name (mcvirt.test.validation_tests.ValidationTests) ... ok
test_method_lock_rpc (mcvirt.test.lock.lock_tests.LockTests)
Test whether locks can be cleared over the RPC ... ok
test_method_lock_escape_return (mcvirt.test.lock.lock_tests.LockTests)
Test whether locks can be cleared and clear_method_lock returns accurateley ... ok
test_valid_user (mcvirt.test.ldap_tests.LdapTests)
Test running a command with valid Ldap credentials ... ok
test_invalid_user (mcvirt.test.ldap_tests.LdapTests)
Test running a command with invalid Ldap credentials ... ok
test_parser (mcvirt.test.ldap_tests.LdapTests)
Test the Ldap options work correctly in the parser ... ok
test_user_search (mcvirt.test.ldap_tests.LdapTests)
Test that getting LDAP usernames takes the user_search attribute into account ... ok

----------------------------------------------------------------------
Ran 78 tests in 147.021s

OK (skipped=21)
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc7f810d3f8>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc7f8136bd8>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc800089518>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc8001aff38>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc7f80b3ef0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc7f8115dd0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc7f810b560>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc8002088c0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc80013c680>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc7f8149ef0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc7f81ab3b0>> ignored
Exception AttributeError: "'NoneType' object has no attribute 'error'" in <bound method SocketConnection.__del__ of <Pyro4.socketutil.SocketConnection object at 0x7fc80021f3b0>> ignored
```

**Comment by MatthewJohn** [comment]
Had issues with vmbr interfaces on ubuntu 18.04. Will leave for now. Meaning that we currently support 14.04, 16.04 and debian 8
